### ISSUE TITLE
Console warning when using lazy-youtube.

### ISSUE THREAD

**Issue by Nalca** [4sllan/nuxt-lazytube#1]
Hello !
Thanks for the nice library !

When using the component **lazy-youtube** (And probably **lazy-vimeo** too) and passing a string to **:src**, it write a warning on the console about being unable to watch a source : 
`LazyYoutube.vue:236 [Vue warn]: Invalid watch source:  https://youtu.be/... 
A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. 
  at <LazyYoutube key=0 src="https://youtu.be/..." class="h-100" > `

The problem :
```typescript
// LazyYoutube.vue, Li 236
watch(props.src, async (val, oldVal) => {
  if (val !== oldVal) {
    resetState();
    getFetchingOembed()
  }
})
```

And here is my solution
```typescript
watch(computed(() => props.src), async (val, oldVal) => {
  if (val !== oldVal) {
    resetState();
    getFetchingOembed()
  }
})
```

**System Info**
- Nuxt: 3.10.3
- Nuxt-lazytube: 0.1.7
- Vue: 3.4.20
- Typescript: 5.3.3

**Comment by 4sllan** [comment]
It has already been implemented in v0.1.8.
